### ISSUE TITLE
Need an example that demonstrates BAM and RTS/CTS communicaitons

### ISSUE THREAD

**Issue by milhead2** [milhead2/python-j1939#1]
While I'm no expert with the library I have written a lot of sending code (to simulate an ECU). I am now working on some code to set and query J1030 memory objects in a bus entity.

**Comment by wigs48** [comment]
Hi  Just found this library and well impressed with it.  Could you post some example on what you have done with it that are a bit more complex than just the few simple examples   you have included.
Anton

**Comment by milhead2** [comment]
Hi Anton,

Sorry to say that I don’t have many more examples.  I took over maintenance if the library when hardbyte dropped it as a protocol within the python-can library.

I use it daily as the j1939 layer between the python robot test framework and python-can and it pretty much meets my needs to date.  I do need to add enhancements to my robot library soon as I’m making smarter ECU simulations disguised as robot framework tests.

Sending a BAM message is easy, just send a data list greater than 8 bytes long to a 0xff address.

I think the RTS/CTS stuff is not quite working (or I have broken it) and I have not had the time to extend them.

I haven’t made any changes since Feb-15 push but am working on one that allows a single script to operate as 2 nodes on the bus (something I need for my test framework).

If you have specific examples of what you are looking for I may be able to rip out some of my library code and toss it into an example but I don’t have anything too grand.

Hope this helps!

Miller

**Comment by bdrehmer** [comment]
I don't have the official J1939 spec and haven't tried using this library yet, but from my reading (like section 4 in https://vector.com/portal/medien/cmc/application_notes/AN-ION-1-3100_Introduction_to_J1939.pdf), the messages sent in the BAM data transmission should be spaced in at least 50ms intervals.  
_throttler_function looks to just be pumping out the messages as quickly as possible as long as there are messages in _long_message_segment_queue.

**Comment by milhead2** [comment]
I pushed a change today that paced outbound BAM and CTS/RTS bolck messages that will limit them to 50 ms pacing.  I haven't tested it rigorously and am kinda wondering what will happen if these transmissions start mixing with other outbound traffic.  My gauges certainly intermix these messages with other traffic, I would like the j1939 lib to do the same thing.   Most of the changes I put in today were for the mem_set application, not really related.

**Comment by milhead2** [comment]
get_ecu_block example will now work via BAM or RTS-CTS style transfers to demonstrate J1939 Request PGN
