### ISSUE TITLE
Python J1939 library usage

### ISSUE THREAD

**Issue by rk00523476** [milhead2/python-j1939#11]
Hi all,
I am new to Python and have good knowledge in J1939 protocol.
We have some J1939 modules developed in LabVIEW and using them in our project, but we are looking to automate the same module using Python, I have gone through Python J1939 library, and I could see there are some functions which can be used to send or receive messages I believe, just for push up I am looking for following code:

1) Connect to PCAN hardware to transmit J1939 messages.
2) Transmit a basic J1939 frame with 8 bytes of data or should be more helpful if could be able to transfer 1785 bytes of data (Large message).

Please help me in getting this code so that it will help me in getting into it and start analyzing more on code.

I have installed J1939 library and using Python 3.8.3 32-bit version of software.

**Comment by milhead2** [comment]
Hi,

You need to install python-can (the specific branch to pick is in the python-j1939 readme).

Here is a simple DM1 sender (You may be able to minimize it further as I cut it down from a more complex tool).  You could also pile up some of the statements like python folks prefer to do...   Your choice!  You should be able to have a DLC up to your 1700 or so.  If you chose a 0xff dest it will send a BAM but if you send to an actual address it will send an RTS and require a handshake to continue.

Take a look at the python-can documentation to see how to configure 'channel' and 'bustype' if running on a PC and PCAN adapter.   In the case that I'm running here I have a PCAN adapter but Linux recognizes it and puts a socketcan layer on top of it automatically.

Good luck!


import time
import j1939

if __name__ == "__main__":

    # code to broadcast a DM1 message at 1 Hz
    # 18FECAFE#FFFF00000000FFFF

    channel = 'can0'
    bustype = 'socketcan'
    sourceaddr = 0xFE
    destaddr = 0xFF


    bus = j1939.Bus(channel=channel, bustype=bustype, timeout=0.01, broadcast=False)

    data = [0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF]
    pgn = j1939.PGN()
    pgn.value = 0xFECA # DM1
    aid = j1939.ArbitrationID(pgn=pgn, source_address=sourceaddr, destination_address=destaddr)
    pdu = j1939.PDU(timestamp=0.0, arbitration_id=aid, data=data, info_strings=None)

    while True:
        bus.send(pdu)
        time.sleep(1)



________________________________

**Comment by milhead2** [comment]
I've added this tiny sender to the examples directory.
