### ISSUE TITLE
import python-j1939 doesn't like the '-' python3

### ISSUE THREAD

**Issue by defied** [milhead2/python-j1939#5]
As the titles says.

`>>> import python-j1939
  File "<stdin>", line 1
    import python-j1939
                 ^

SyntaxError: invalid syntax
>>>`

**Comment by milhead2** [comment]
Take a look at the samples, After installation I only import the j1939 object not the full package name.  This is the way that python-can works as well and what I patterned it after

$ python
Python 3.7.0 (default, Aug  6 2018, 11:20:51) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import j1939
>>> dir(j1939)
['ADDRESS_UNCLAIMED', 'ArbitrationID', 'Bus', 'BusABC', 'CM_ABORT_J1939_71_RESERVED_END', 'CM_ABORT_J1939_71_RESERVED_START', 'CM_ABORT_NO_RESOURCES', 'CM_ABORT_SAE_RESERVED_END', 'CM_ABORT_SAE_RESERVED_START', 'CM_ABORT_SESSION_IN_PROGRESS', 'CM_ABORT_TIMEOUT', 'CM_ABORT_UNKNOWN', 'CM_MSG_TYPE_ABORT', 'CM_MSG_TYPE_BAM', 'CM_MSG_TYPE_CTS', 'CM_MSG_TYPE_EOM_ACK', 'CM_MSG_TYPE_RTS', 'CanError', 'DESTINATION_ADDRESS_GLOBAL', 'DESTINATION_ADDRESS_NULL', 'Empty', 'INDUSTRY_GROUP_AGRICULTURAL', 'INDUSTRY_GROUP_CONSTRUCTION', 'INDUSTRY_GROUP_GLOBAL', 'INDUSTRY_GROUP_HIGHWAY', 'INDUSTRY_GROUP_INDUSTRIAL', 'INDUSTRY_GROUP_MARINE', 'INDUSTRY_GROUP_RESERVED_1', 'INDUSTRY_GROUP_RESERVED_2', 'Message', 'Node', 'NodeName', 'Notifier', 'PDU', 'PGN', 'PGN_AC_ADDRESS_CLAIMED', 'PGN_AC_COMMANDED_ADDRESS', 'PGN_REQUEST_FOR_PGN', 'PGN_TP_CONNECTION_MANAGEMENT', 'PGN_TP_DATA_TRANSFER', 'PGN_TP_SEED_REQUEST', 'Queue', 'RawCanBus', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'arbitrationid', 'canListener', 'canNotifier', 'can_set_logging_level', 'ch', 'chformatter', 'constants', 'copy', 'fileHandler', 'genkey', 'get_mem_object', 'j1939', 'j1939Listner', 'j1939_industry_groups', 'lLevel', 'logger', 'logging', 'node', 'nodename', 'notifier', 'pdu', 'pgn', 'pgn_strings', 'pprint', 'print_function', 'request_pgn', 'security', 'send_pgn', 'set_mem_object', 'threading', 'time', 'utils']
>>>

**Comment by defied** [comment]
Okay, thanks. Ideally, that should be cleaner.
