### ISSUE TITLE
Windows installation error

### ISSUE THREAD

**Issue by wang701** [milhead2/python-j1939#9]
For working with Vector hardware, I need to use Windows 10 to run this library.

In Windows Powershell, I cd'ed into the cloned directory and installed the library using `pip install .`. But when I tried to import the library using `import j1939`, the library gives error on this [line](https://github.com/milhead2/python-j1939/blob/master/j1939/__init__.py#L54). Specifically,
```
fileHandler = logging.handlers.RotatingFileHandler('/tmp/j1939.log', \
```

The reason is that the specified log file path works only for unix like systems. My test environment:

OS: Windows 10 Pro
Version: 10.0.18363 Build 18363
Python version: 3.7.7

**Comment by wang701** [comment]
Please see proposed fix in https://github.com/milhead2/python-j1939/pull/10.

**Comment by milhead2** [comment]
WooHoo!   9 errors fixed in a few years....

Thank you very much for detecting this, I tend to use PCAN on PC's (and on Linux) but this would block all Windows users..   Nice Catch and thanks for the Pull request.

Miller

**Comment by milhead2** [comment]
I'm closing this issue, Feel free to file another if needed!
